---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v1.4.1
  secretRef:
    # References the default flux-system Git auth secret (PAT)
    name: flux-system
  timeout: 60s
  url: https://github.com/kubernetes-sigs/gateway-api.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 10m0s
  # Override path per cluster
  # Existing kustomization.yaml in path, uses ./standard by default
  path: ./config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
