---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    # References the default flux-system Git auth secret (PAT)
    name: flux-system
  timeout: 60s
  url: https://github.com/barstown/kubernetes-secrets.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      # References a secret containing the sops age private key
      name: sops-age
  interval: 10m0s
  # Override path per cluster
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-secrets
