---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
  patches:
  - patch: |-
      - op: add
        path: /spec/values/l2announcements
        value: {enabled: true}
    target:
      kind: HelmRelease
      name: cilium
  - patch: |-
      - op: add
        path: /spec/values/l2podAnnouncements
        value: {enabled: true, interface: "ens18"}
    target:
      kind: HelmRelease
      name: cilium
  - patch: |-
      - op: add
        path: /spec/values/externalIPs
        value: {enabled: true}
    target:
      kind: HelmRelease
      name: cilium
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: external-dns
        namespace: external-dns
      spec:
        values:
          image:
            repository: registry.k8s.io/external-dns/external-dns
            tag: v0.20.0
          env:
            - name: EXTERNAL_DNS_PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: EXTERNAL_DNS_PIHOLE_PASSWORD
            - name: EXTERNAL_DNS_PIHOLE_SERVER
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: EXTERNAL_DNS_PIHOLE_SERVER
          extraArgs:
            - --pihole-api-version=6
            - --pihole-tls-skip-verify=true
          policy: upsert-only
          provider:
            name: pihole
          registry: noop
          sources:
            - gateway-httproute
            - gateway-tlsroute
            - ingress
            - service
    target:
      kind: HelmRelease
      name: external-dns

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt
    - patch: |
        # - op: replace
        #   path: /spec/blocks/0/start
        #   value: "10.0.10.8"
        - op: add
          path: /spec/blocks/-
          value:
            start: "10.0.15.100"
            stop: "10.0.15.150"
      target:
        kind: CiliumLoadBalancerIPPool
        name: cilium-lb-ippool
