---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 12h
  url: https://kubernetes-sigs.github.io/external-dns

---
# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pihole.md
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values: {}
