---
apiVersion: v1
kind: Namespace
metadata:
  name: freenas-api-iscsi
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: freenas-api-iscsi
  namespace: freenas-api-iscsi
spec:
  interval: 12h
  url: https://democratic-csi.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freenas-api-iscsi
  namespace: freenas-api-iscsi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: freenas-api-iscsi
        namespace: freenas-api-iscsi
      interval: 12h
  values: {}
