---
# https://github.com/getsops/sops?tab=readme-ov-file#513settings
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age17grtxlahavxq6sacmu9sj355lasjvkxc8ekmy59ejzf68quk5dhstfgvj6
