apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
data:
    age.agekey: ENC[AES256_GCM,data:MbUZAQiX7n20Y4jYfK3IawQkqqAVUPLoAsGsSCdyOyhaRD9kjD/gUNFGx1/hI+DGnFT1r4ih0+3cyJBgCn7jkR2yQu9ZrBBbfci5lAN6IttbnDnqXM6PzmyT0vmk/SPvnEgbqA==,iv:codI5piMFvWnUSU/rv+NS3ysZv6ValZ2kw8Y9STsYzE=,tag:aR3O8IRXbUVTfKbe/HdPKQ==,type:str]
sops:
    age:
        - recipient: age17grtxlahavxq6sacmu9sj355lasjvkxc8ekmy59ejzf68quk5dhstfgvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeGI4dUxKL3cxU2twV3Fa
            SzJobUVyamYwM2dyalYzR1pFRFpuWW9ISmtvClFibGJjTUhoc3UvZG5VenhINm43
            MGdQM1o4RU1xbmJDQ0NHZjJmd2FOa1EKLS0tIEJqcG1XNGlzRUdoQ3VhR3UzUXdp
            VndPK2hGWm1nbk0zcVp5QzdDN1RxbUkKVYXP8PRDxsXd2JrE1QTs9S0pTNuyechV
            b+/DvULGB1W4IF3pbCTS20KGRPfP/8P1XgeJ+JGZ+6jWVHSVLyNiMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T18:40:38Z"
    mac: ENC[AES256_GCM,data:rWovRKSSv/a/ccZEJs7YF2fROOIYo+/NDSk3+Cq6zDJt45wGJT4vVrBJ2bwu/68qTVwcWL9GQApquYuuUfQqr9qpFrs3Y0iL1Nm6zGacl1++FsTZWepN4t/4ckqxmbE178S84W9XJX98rg5TYM+fSbklvs40AnUwENJTY4eSKWI=,iv:Otuqa2nVaa3si/7iqYeS0DrDG6KWCs7sl04CEpDB9vE=,tag:0OPc7GJZHK5ZGphPgB3X4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
