apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
data:
  age.agekey: ENC[AES256_GCM,data:Fe0h4UD4kPzc5C3D8UAtFOTtMUlHnRe4hrZMbdopaek1/aT52/V5za9PLsehsbsJ98lTefLGNkzsYrgBsT3hQqQ0raRs1Kt47cVAISWSm2rGRmZM9EaQTEhAR5KizfCJdTAYDQ==,iv:h4uu9hUYOWur2dr3yK85WKi9IPtuP6RW5pQp71Va9QI=,tag:C6eFkW4QFvdPlCxi6MR+Zw==,type:str]
sops:
  age:
    - recipient: age1sfg4e25g6temu7xakcuud0m47ynn54mrgg08ucjuquptpclc0epq38w9xt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZU1hVHYzOUdlU2R0QmFo
        MzFwcTlhdHByT1VqZlFySHcxZ3Nqc0taeENzClVSUmlaOHI3NXRiQzFUdTNaNnV5
        T09tUGprRVlxUGRQQzFoMEhGVnc2MDQKLS0tIDY2YnJWVzRneE1OY2R6NWlQV1g3
        OGhzTXh4ZXArWWU2cHU0VGFuN3QyazAKQPmPFZgR9ItMQoz9S68Z3A43xHw/Bdg6
        vt/czLxdQniMpMG3Y2JRJvUaor5OvNvVE3g9voCeEar0X9q8cgzcfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T22:56:47Z"
  mac: ENC[AES256_GCM,data:PpNyUMYLeDnrfUFc2A4TTyn7oaEYZ3FVPnoj5L91utPpftxwhBigd0KqXV/45k0QbnKI9HdGqjCUIQGQKdT7BgeZ7MV99UpISgJ4JsmwTRJh4HtKW2gp8Q8YZjRujvnI6UXiIOwuCjHBYZvq9WfXvWNnWMeO3Lx8IFMvAkMwABg=,iv:a+hTQPGEXWry/I9XklxoushAI8yHuz4IeWpk1Zb+iOk=,tag:kcTbKkZL+k33+EGZ1ArMUA==,type:str]
  encrypted_regex: ^(data|stringData|email)$
  version: 3.11.0
