apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
data:
    age.agekey: ENC[AES256_GCM,data:ETlWmyMSrzWrIerkS3fZcclMYCYdFfCGziMjQToByueTKLkwGkffc8kjiChWVEih6XSkU6W26jR/60R3kXLi2z73dWIsowpIuZa1Nj00ncQlnGsp9ZXLSNPsdsHAZM756Ex3aQ==,iv:QwcjTNu4EYLwSujV5QO8pVNqeKyz1mOfs8IJgxEGvPc=,tag:kjKJS7HcaP/m0yPwGWg28g==,type:str]
sops:
    age:
        - recipient: age1sfg4e25g6temu7xakcuud0m47ynn54mrgg08ucjuquptpclc0epq38w9xt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSFhCelhoYWtpdjg1bm4w
            UmxVNE9ldVJnTFZqbER0azZvbjR4SkRoaDJZCjZQUWFNUnVXWWMwRXZHUHh4dUhH
            UWNrcHhsaWowbnRNM1JwOW9WT0tpTGsKLS0tIGwzaVQ1MjNMSk1LOGlUQVVzUElX
            OUh1b0xTS2JsMEUvVXpRdjEwN0NXQncKsvSx9L5KbcALso9rf9Qc+s00HMs6K15A
            VkLnZVh++TGKudJWpRUvqRJSj+pEbPQyEwIg7kHBrnOSMNiY7oTRuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T18:49:41Z"
    mac: ENC[AES256_GCM,data:Dr8TS7RsQAETO+f9DZhEuCdzX2A20GQ3qYPlNJKvBHX568XFew/PBJyXDTakar+8bn6MHFtHjlqYeDu6SEBPvwTw2jlu5bh0A8bknlqzDz0h4QrvY7dXn5ISx8u3CCkcdmKRhFLXrDQPMLHAEL8sn21O4l8EJZVGwosF4pRUjO0=,iv:3sCg7a0SKDWBJhKqLdUBUoUfsGcMXv/Mlwe1/I9u2Dk=,tag:KQLdihGStSz81/XFHBh0ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
